service: stakepool-cron
frameworkVersion: '2'
useDotenv: true
provider:
    name: aws
    region: ap-south-1
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221

functions:
    pingContractTestnet:
        handler: handler.pingContractTestnet
        events:
            - schedule:
                  rate: cron(*/2 * * * ? *)
                  enabled: true
